### ISSUE TITLE
How to switch to next item in playlist

### ISSUE THREAD

**Issue by nitinmishra27** [veeso/android-media-player-standalone-library#1]
I've managed to run the player and using playlist from here "http://sfworx.com/development/test.json" but i can't get to know any API so that i can go to the next track in "JSON API", in simple words how may i seek to next and previous tracks.

Help is highly appreciated

**Comment by andreimarinescu** [comment]
Hi, @androlizer,

The player documentation currently available can be accessed here: http://veeso.github.io/android-media-player-standalone-library/. Specifically, to skip content units, you can call APSMediaPlayer.getInstance().skip();

Let me know if this solves your issue.

**Comment by nitinmishra27** [comment]
@andreimarinescu thanks for quick `turnaround`. this solved my issue and for other coder. People can use `APSMediaPlayer.getInstance().back()` to goback to previous track.

Thanks

**Comment by andreimarinescu** [comment]
Good to know it works. Let us know if you encounter any other issues!
