### ISSUE TITLE
play directly from url....

### ISSUE THREAD

**Issue by sirvon** [veeso/android-media-player-standalone-library#3]
How do you configure the builder to just play a video from a single url?

I just want to play a local file or one url that I assign locally.

how to proceed?

thanks

**Comment by andreimarinescu** [comment]
Hi, @sirvon. Sorry for the late reply, Github isn't our main outlet for providing support yet.

There's multiple ways of doing this, either by passing a simple JSON to MediaBuilder and using the configureFromData method, or working with Java objects directly. From past implementation I've seen that this is generally the preferred method, here's a snippet that should work:

```
    ArrayList<APSMediaEvent> mediaUnits = new ArrayList<>();
    APSMediaUnit unit = new APSMediaUnit();
    unit.url = "http://devimages.apple.com/iphone/samples/bipbop/bipbopall.m3u8";
    HashMap<String, Object> controlsParams = new HashMap<>();
    controlsParams.put(APSMediaPlayerControlsOverlayController.kAPSControlsComponents,
            APSMediaPlayerControlsOverlayController.APSPlaybackControl|
                    APSMediaPlayerControlsOverlayController.APSCurrentTimeControl|
                    APSMediaPlayerControlsOverlayController.APSTimeSliderControl|
                    APSMediaPlayerControlsOverlayController.APSTotalTimeControl|
                    APSMediaPlayerControlsOverlayController.APSFullScreenControl);
    unit.controlsParameters = controlsParams;
    mediaUnits.add(unit);
    //start the playback
    APSMediaPlayer.getInstance().playMediaUnits(mediaUnits);
```

Let me know if this solves your issue.
