### ISSUE TITLE
Video image

### ISSUE THREAD

**Issue by trbsi** [veeso/android-media-player-standalone-library#6]
Hi.

Is it possible to put default image before video plays. As YouTube has to upload custom thumbnail when video is loaded and not played yet?

**Comment by andreimarinescu** [comment]
Hi, @trbsi,

Yes, you should:
- disable autoplay
- add an image overlay to the content unit, starting at 0, with the thumbnail you wish to show
- add another image overlay, with the clickthrough URL: apsplayer://play. This image overlay should be a transparent PNG file, something resembling a play button.

All of this can be accomplished by either using JSON configuration, or working with the Java API. Let me know if this helps.

**Comment by trbsi** [comment]
Thanks, I'll try that. I used your demo app from github. My Json output is belowt. I put autoplay to false but it still autoplays my video. What am I doing wrong?

```
{
  "content": [
    {
      "url": "http://cms.born2invest.com/uploads/video/video.mp4",
      "autoplay": false
    }
  ]
}
```

**Comment by trbsi** [comment]
Link to json file http://cms.born2invest.com/example1.json

**Comment by andreimarinescu** [comment]
Hi, @trbsi. Looking at this right now, I'll be right back with info on the correct JSON syntax (or an SDK update if there's a bug).

**Comment by andreimarinescu** [comment]
Ok, so I made a gist that you should be able to use in order to achieve this functionality. Let me know if this works for you as well.

By the way, this should work with your current version of the SDK, but I recommend upgrading to 2.0.15 (just released on maven). I've noticed that when using bumpers, 2.0.13 was also showing the loader animation (fixed in 2.0.15).

You can check out the gist at: https://gist.github.com/andreimarinescu/5751b5de7b2a9b8758fd

**Comment by trbsi** [comment]
Cool It's working. But one thing I don't understand is why is "autoplay" on true, but video doesn't autoplay on start?

Plus, skip button backgroundcolor doesn't work
    "skipButton":
    {
        "backgroundColor":"ffffff",
        "defaultOffset":"5"
    }

**Comment by andreimarinescu** [comment]
Good to know this is working for you!

The video doesn't autoplay on start as autoplay is referring to the first content unit. The way the example JSON works, it inserts another empty unit before the main one, that only contains 2 overlays (this type of unit is called a bumper).

Regarding the skipButton, could you post your full json configuration, in a separate Github issue? (I'd rather keep threads clean, one issue/thread). Thanks!
