### ISSUE TITLE
skipButton extra options

### ISSUE THREAD

**Issue by trbsi** [veeso/android-media-player-standalone-library#7]
I'm using this json to add video to my app and it's working, but when I set "backgroundColor"
 to skip button app crashes.

Here is gist
https://gist.github.com/trbsi/d8c2b089425feb540d36#file-skipbutton-json

And here is file
http://cms.born2invest.com/example1.json

**Comment by andreimarinescu** [comment]
Closing this as the issue as it seems to be working in the current versions of the player and the GH issue is quite old. Please contact our support team in case you need any help with the Veeplay SDK.
